### ISSUE TITLE
add feature about exclude some folder

### ISSUE THREAD

**Issue by JackyTianer** [ant-tool/postcss-plugin-px2rem#9]
当引入第三方插件的时候，不想对第三方插件进行px2rem操作，但是又想使用其他postcss插件，想添加一个参数exclude用于忽略指定目录不进行px2rem操作

**Comment by JackyTianer** [comment]
@pigcan 能帮忙发一个版本吗，谢谢

**Comment by pigcan** [comment]
@JackyTianer 0.8.0
